# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addgenre.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class addGenreForm(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(315, 114)
        self.genreAddEdit = QtWidgets.QLineEdit(Dialog)
        self.genreAddEdit.setGeometry(QtCore.QRect(80, 20, 201, 21))
        self.genreAddEdit.setObjectName("genreAddEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label.setObjectName("label")
        self.writeGenre = QtWidgets.QPushButton(Dialog)
        self.writeGenre.setGeometry(QtCore.QRect(190, 60, 101, 21))
        self.writeGenre.setObjectName("writeGenre")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Название"))
        self.writeGenre.setText(_translate("Dialog", "Сохранить"))
