# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(788, 629)
        self.doBtn = QtWidgets.QPushButton(Form)
        self.doBtn.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.doBtn.setObjectName("doBtn")
        self.output = QtWidgets.QTableWidget(Form)
        self.output.setGeometry(QtCore.QRect(10, 50, 771, 571))
        self.output.setObjectName("output")
        self.output.setColumnCount(0)
        self.output.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменение элементов"))
        self.doBtn.setText(_translate("Form", "Добавить"))
