# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_films2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(831, 443)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 181, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.year_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.year_line.setObjectName("year_line")
        self.verticalLayout.addWidget(self.year_line)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.name_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.name_edit.setObjectName("name_edit")
        self.verticalLayout.addWidget(self.name_edit)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.length_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.length_edit.setObjectName("length_edit")
        self.verticalLayout.addWidget(self.length_edit)
        self.go_btn = QtWidgets.QPushButton(Form)
        self.go_btn.setGeometry(QtCore.QRect(60, 200, 101, 31))
        self.go_btn.setObjectName("go_btn")
        self.output = QtWidgets.QTableWidget(Form)
        self.output.setGeometry(QtCore.QRect(230, 20, 581, 411))
        self.output.setObjectName("output")
        self.output.setColumnCount(0)
        self.output.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Год"))
        self.label_2.setText(_translate("Form", "Название"))
        self.label_3.setText(_translate("Form", "Длина"))
        self.go_btn.setText(_translate("Form", "Пуск"))
