# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 584)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.output = QtWidgets.QTableWidget(self.tab)
        self.output.setGeometry(QtCore.QRect(10, 50, 771, 491))
        self.output.setObjectName("output")
        self.output.setColumnCount(0)
        self.output.setRowCount(0)
        self.deleteBtn = QtWidgets.QPushButton(self.tab)
        self.deleteBtn.setGeometry(QtCore.QRect(270, 10, 111, 31))
        self.deleteBtn.setObjectName("deleteBtn")
        self.updateBtn = QtWidgets.QPushButton(self.tab)
        self.updateBtn.setGeometry(QtCore.QRect(140, 10, 111, 31))
        self.updateBtn.setObjectName("updateBtn")
        self.doBtn = QtWidgets.QPushButton(self.tab)
        self.doBtn.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.doBtn.setObjectName("doBtn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.updateBtn_2 = QtWidgets.QPushButton(self.tab_2)
        self.updateBtn_2.setGeometry(QtCore.QRect(140, 10, 111, 31))
        self.updateBtn_2.setObjectName("updateBtn_2")
        self.deleteBtn_2 = QtWidgets.QPushButton(self.tab_2)
        self.deleteBtn_2.setGeometry(QtCore.QRect(270, 10, 111, 31))
        self.deleteBtn_2.setObjectName("deleteBtn_2")
        self.doBtn_2 = QtWidgets.QPushButton(self.tab_2)
        self.doBtn_2.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.doBtn_2.setObjectName("doBtn_2")
        self.output_2 = QtWidgets.QTableWidget(self.tab_2)
        self.output_2.setGeometry(QtCore.QRect(10, 50, 771, 491))
        self.output_2.setObjectName("output_2")
        self.output_2.setColumnCount(0)
        self.output_2.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменение элементов"))
        self.deleteBtn.setText(_translate("Form", "Удалить"))
        self.updateBtn.setText(_translate("Form", "Изменить"))
        self.doBtn.setText(_translate("Form", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Фильмы"))
        self.updateBtn_2.setText(_translate("Form", "Изменить"))
        self.deleteBtn_2.setText(_translate("Form", "Удалить"))
        self.doBtn_2.setText(_translate("Form", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Жанры"))
