# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'olimpiada.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(618, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 571, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.school_num = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.school_num.setObjectName("school_num")
        self.horizontalLayout.addWidget(self.school_num)
        self.class_num = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.class_num.setObjectName("class_num")
        self.horizontalLayout.addWidget(self.class_num)
        self.go_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.go_btn.setObjectName("go_btn")
        self.horizontalLayout.addWidget(self.go_btn)
        self.output = QtWidgets.QTableWidget(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(20, 60, 581, 461))
        self.output.setObjectName("output")
        self.output.setColumnCount(0)
        self.output.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 618, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.go_btn.setText(_translate("MainWindow", "Узнать результаты"))
