# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(532, 710)
        self.image_output = QtWidgets.QLabel(Dialog)
        self.image_output.setGeometry(QtCore.QRect(120, 10, 291, 381))
        self.image_output.setText("")
        self.image_output.setObjectName("image_output")
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setGeometry(QtCore.QRect(184, 410, 161, 41))
        self.label_name.setObjectName("label_name")
        self.labelTitle = QtWidgets.QLabel(Dialog)
        self.labelTitle.setGeometry(QtCore.QRect(10, 460, 521, 20))
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.labelAuthor = QtWidgets.QLabel(Dialog)
        self.labelAuthor.setGeometry(QtCore.QRect(10, 530, 511, 20))
        self.labelAuthor.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAuthor.setObjectName("labelAuthor")
        self.label_name_2 = QtWidgets.QLabel(Dialog)
        self.label_name_2.setGeometry(QtCore.QRect(210, 480, 101, 41))
        self.label_name_2.setObjectName("label_name_2")
        self.labelYear = QtWidgets.QLabel(Dialog)
        self.labelYear.setGeometry(QtCore.QRect(10, 600, 511, 20))
        self.labelYear.setAlignment(QtCore.Qt.AlignCenter)
        self.labelYear.setObjectName("labelYear")
        self.label_name_3 = QtWidgets.QLabel(Dialog)
        self.label_name_3.setGeometry(QtCore.QRect(160, 550, 221, 41))
        self.label_name_3.setObjectName("label_name_3")
        self.labelGenre = QtWidgets.QLabel(Dialog)
        self.labelGenre.setGeometry(QtCore.QRect(10, 670, 511, 20))
        self.labelGenre.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGenre.setObjectName("labelGenre")
        self.label_name_4 = QtWidgets.QLabel(Dialog)
        self.label_name_4.setGeometry(QtCore.QRect(210, 620, 101, 41))
        self.label_name_4.setObjectName("label_name_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Информация о книге"))
        self.label_name.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Название</span></p></body></html>"))
        self.labelTitle.setText(_translate("Dialog", "TextLabel"))
        self.labelAuthor.setText(_translate("Dialog", "TextLabel"))
        self.label_name_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Автор</span></p></body></html>"))
        self.labelYear.setText(_translate("Dialog", "TextLabel"))
        self.label_name_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Год выпуска</span></p></body></html>"))
        self.labelGenre.setText(_translate("Dialog", "TextLabel"))
        self.label_name_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Жанр</span></p></body></html>"))
