# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'library.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 561)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(30, 40, 111, 21))
        self.comboBox.setObjectName("comboBox")
        self.searchLine = QtWidgets.QLineEdit(Form)
        self.searchLine.setGeometry(QtCore.QRect(30, 90, 201, 21))
        self.searchLine.setObjectName("searchLine")
        self.goBtn = QtWidgets.QPushButton(Form)
        self.goBtn.setGeometry(QtCore.QRect(280, 20, 171, 91))
        self.goBtn.setObjectName("goBtn")
        self.output = QtWidgets.QListWidget(Form)
        self.output.setGeometry(QtCore.QRect(30, 160, 421, 381))
        self.output.setObjectName("output")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Каталог библиотеки"))
        self.goBtn.setText(_translate("Form", "Искать"))
